[package]
name = "wallet"
version = "0.1.0"
authors = ["KatoMono Enkeli <k4t0mono@gmail.com>"]
edition = "2018"

[dependencies]
serpentine = { path = "../utils" }
log = "^0.4"
simplelog = "^0.5"
rand = "^0.6"
byteorder = "^1.3"
crc = "^1.0.0"
