[package]
name = "serpentine"
version = "0.1.0"
authors = ["KatoMono Enkeli <k4t0mono@gmail.com>"]
edition = "2018"

[dependencies]
log = "^0.4"
byteorder = "^1.3"
crc = "^1.0.0"
bincode = "1.1.1"
serde_derive = "1.0.88"
serde = "1.0.88"
